name: Build Application
on:
  push:
    branches:
      - main

jobs:
  push:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}

      - name: Build application
        run: |
          mvn clean package

      - name: Upload ci-server
        uses: actions/upload-artifact@v1
        with:
          name: ci-server-1.0-SNAPSHOT.jar
          path: target/ci-server-1.0-SNAPSHOT.jar
